<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Datos Personales Bsicos</name>
   <tag></tag>
   <elementGuidId>989c3879-6bfb-433f-b3e5-4bec196bce4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ws-form-1']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8de7f8a6-5790-426e-bb46-b2b51e646b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Datos Personales Básicos</value>
      <webElementGuid>2397ae25-3650-4918-99d1-2f0066d5d050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ws-form-1&quot;)/h2[1]</value>
      <webElementGuid>0b12f90f-f981-4e2e-b7f1-c0a41f6847a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ws-form-1']/h2</value>
      <webElementGuid>d8fef66a-cb86-479d-90c9-bb2bacaaab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacto'])[2]/following::h2[1]</value>
      <webElementGuid>27b9fc37-0f54-4502-8406-17c0f26d2ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colegio'])[2]/following::h2[1]</value>
      <webElementGuid>065e0e34-1ff0-4fbb-a6fc-13b7c26bd312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre:'])[1]/preceding::h2[1]</value>
      <webElementGuid>7be9ff1b-1441-401b-bc76-2205d88d6244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide a valid nombre:.'])[1]/preceding::h2[1]</value>
      <webElementGuid>f88d8823-4a61-4591-a121-a16d2aa813dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Datos Personales Básicos']/parent::*</value>
      <webElementGuid>c7921c8c-d509-49c1-ba16-acf45a15aeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9bef264c-87e7-4805-ba57-03fbb08ffaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Datos Personales Básicos' or . = 'Datos Personales Básicos')]</value>
      <webElementGuid>7dba2cfc-4d12-4700-aa1b-a47db6d75282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
