<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Direccin_field_28</name>
   <tag></tag>
   <elementGuidId>77e17c90-bd6a-4922-99ec-a73f0268f9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wsf-1-field-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1a9e7e0d-b63e-46c4-b905-84e86b167e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-28</value>
      <webElementGuid>dab8ac4d-1f6b-4e1b-9a03-de283d3e3d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_28</value>
      <webElementGuid>3e3df3e7-0874-42dc-8691-b84408c3dcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>9c290d7c-3c90-4024-9234-66c4c0b2d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textarea-toolbar</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>8241b2d6-b979-4b88-a091-e042a6670e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>f8127d78-af4e-4d16-802b-f07a87234500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>wsf-1-help-28</value>
      <webElementGuid>84e2191c-3665-4f8b-ac94-9eee9cd69a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-28</value>
      <webElementGuid>75cd1662-524c-477c-a47a-f99d80b81b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-28&quot;)</value>
      <webElementGuid>aced258e-b777-4853-9b39-c52694560a7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wsf-1-field-28']</value>
      <webElementGuid>91a9a07c-91de-4971-846c-1ce2e3e12e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-28']/textarea</value>
      <webElementGuid>9db398a5-7188-4e7a-aedb-4202ae0e773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cbcd20a4-48b1-4f9c-92ce-ccb4c51690f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wsf-1-field-28' and @name = 'field_28' and @placeholder = 'Email']</value>
      <webElementGuid>290bd0a4-3be2-4217-aa9f-8edf4251654c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
