<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Integers only_intSelection</name>
   <tag></tag>
   <elementGuidId>240407d0-750c-44ba-8773-8c576a285eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='integerSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#integerSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>992ad2e0-de8c-4530-aeda-da5179b17f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>integerSelect</value>
      <webElementGuid>93d61e8e-5a75-4ec0-90a9-7fec06cf9874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>intSelection</value>
      <webElementGuid>4b69fd5c-b01f-41e1-b71d-d1d066dddff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element checkbox</value>
      <webElementGuid>ba57ad1e-2792-4a2b-a556-4d7699619448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>905cdcd2-c3b5-45f1-9f02-ccc9e16f2014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19d8a792-60da-4f76-8cee-58b134e3b519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;integerSelect&quot;)</value>
      <webElementGuid>fbb44c0e-29ea-41d9-81fc-60e2dedadec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='integerSelect']</value>
      <webElementGuid>cd72cf16-4bf2-46c7-9932-029c1d943f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='answerForm']/div[2]/div[2]/span/input</value>
      <webElementGuid>41b57e44-e5a1-4ca7-93f1-eb9a6cd48fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>5307d0c2-840a-45f1-9e51-9e115602730d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'integerSelect' and @name = 'intSelection' and @type = 'checkbox']</value>
      <webElementGuid>51249b27-9452-4011-93ad-9d908f0dca7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
