<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Prototype</name>
   <tag></tag>
   <elementGuidId>571a2962-2c61-4ece-91d6-d8ac6513d816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectBuild']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectBuild</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c537202-f241-40da-a8dc-630d783ee643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>3e64cab2-9887-4f9c-940b-a70d1f6ab262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>9cd05975-6095-4e02-95b5-1001bcb27bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>cc75ed97-3d0b-41db-aaf7-68060fd4fa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>buildChanged(this.preset)</value>
      <webElementGuid>c905bdaf-28af-4b7a-8448-42713d6f6dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      </value>
      <webElementGuid>8041c6a0-8c95-4ba1-ba50-0dbd4cc0ffd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectBuild&quot;)</value>
      <webElementGuid>a8e19b1c-65bc-4adc-b865-454d884f0616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectBuild']</value>
      <webElementGuid>37d65709-6025-4349-b57b-5646d1a8634e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-body']/div/div/div/div/div[2]/select</value>
      <webElementGuid>09aac9c5-0d8d-425b-adae-9cdf9eaf55ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build'])[1]/following::select[1]</value>
      <webElementGuid>090f8a9a-881a-4218-b7a7-8d3e815c4ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prototype'])[1]/following::select[1]</value>
      <webElementGuid>0f2e21bc-507e-4970-a46a-4ded6dcfb312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::select[1]</value>
      <webElementGuid>a6c73384-75ff-4bb6-9362-7a3b3a9c827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First number'])[1]/preceding::select[1]</value>
      <webElementGuid>8d3a8351-d897-40b9-9ce5-36f3febe6fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ddd98f27-faf2-46f3-873b-d5144818bd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectBuild' and @name = 'selectBuild' and (text() = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ' or . = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ')]</value>
      <webElementGuid>c0971141-b4c4-4317-bf3e-246923eaa442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
