<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Add</name>
   <tag></tag>
   <elementGuidId>5d003798-6d07-4227-a541-f9a8f0fdddbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOperationDropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectOperationDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df9e0f4b-7dd2-4988-b94c-a5c7873ae73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>03d9ed82-20c3-431a-9221-e2d79f20c29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOperationDropdown</value>
      <webElementGuid>093ccaa1-6961-4d14-af08-b455494ae63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectOperation</value>
      <webElementGuid>ad8185c4-a3e9-4a65-a52f-05bb8443e8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>operationChanged(this.preset)</value>
      <webElementGuid>35a1ed02-129b-4b56-b9b6-e2e90ccadcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        </value>
      <webElementGuid>b066fb44-0e05-451a-8b28-98e50538ab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOperationDropdown&quot;)</value>
      <webElementGuid>06a8a448-d680-4978-9ab9-9951c6b54298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOperationDropdown']</value>
      <webElementGuid>bb18d978-bf76-4549-927d-baaf1821c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[3]/div[2]/select</value>
      <webElementGuid>1686770b-7641-45a1-936b-98dccf98b2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::select[1]</value>
      <webElementGuid>bf6757a6-e238-4f36-a85f-c0e040e0f91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second number'])[1]/following::select[1]</value>
      <webElementGuid>19a8c8f8-c612-4d2e-8f7e-83347751dbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculating ...'])[1]/preceding::select[1]</value>
      <webElementGuid>721a98ff-dd6d-4ce0-9ebb-5df0e54526ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer'])[1]/preceding::select[1]</value>
      <webElementGuid>65e7c72f-3874-4b2a-b581-f014c0c3bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>b273a0c4-ed47-4ab5-9c68-c0ff3721e22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOperationDropdown' and @name = 'selectOperation' and (text() = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ' or . = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ')]</value>
      <webElementGuid>13b4464d-ab9f-41d8-b84f-7d8b9fb7a6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
