<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Integers only_intSelection</name>
   <tag></tag>
   <elementGuidId>ab2db692-9d5e-404b-8acd-c08553eb60a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='integerSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#integerSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79917c2-b850-423f-85b2-9a5735a314ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>integerSelect</value>
      <webElementGuid>0b0bcece-3c5a-45ae-9208-fb8134feb842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>intSelection</value>
      <webElementGuid>24755bfe-0c78-4af4-992a-3748d6eb3d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element checkbox</value>
      <webElementGuid>25311e9d-c526-4c24-85e3-7b6a8ec17a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>faa6c86d-2abb-4ccd-bf7b-03347e8869fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cdf0b281-4fd0-4001-a7f5-d19090defd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;integerSelect&quot;)</value>
      <webElementGuid>533a42bd-d1f1-41a8-b4fd-731b7e8e8f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='integerSelect']</value>
      <webElementGuid>acfb2910-5a00-4ea6-9924-5b3d03046b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='answerForm']/div[2]/div[2]/span/input</value>
      <webElementGuid>ca485a62-b89e-4945-8e56-0a27203a37c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d181d980-23b1-43b6-b19f-c32670b7780f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'integerSelect' and @name = 'intSelection' and @type = 'checkbox']</value>
      <webElementGuid>11eab635-85a8-4064-b4e7-53618ae8b9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
