<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First number_number1</name>
   <tag></tag>
   <elementGuidId>492fa4cd-3035-40f8-a9f9-32429fb50731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number1Field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#number1Field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0c00b4b-d8d5-4396-abbc-4c9685b2558c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number1Field</value>
      <webElementGuid>693d3614-5aab-4761-b910-6551d876acac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number1</value>
      <webElementGuid>c3de9bb2-d5bd-4da9-8953-4cd05492d9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>387185c7-7c4d-4df0-a907-8ceaa2a24bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f7d85f8-c4fe-40ae-b74f-6540c02deb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ee405840-7d03-458a-8cc9-5a78fd3ba78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number1Field&quot;)</value>
      <webElementGuid>751bd588-a556-408c-a385-6f266d8e4d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number1Field']</value>
      <webElementGuid>c425cea1-3400-4354-85d4-bd6bc195c703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div/div[2]/input</value>
      <webElementGuid>a471e256-c510-424c-9703-d358ab59d000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>350aea1c-929f-47f8-acb3-f97e8f179fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number1Field' and @name = 'number1' and @type = 'text']</value>
      <webElementGuid>8c4eb507-957f-461c-b12e-e2987f2aee2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
