<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Answer_numberAnswer</name>
   <tag></tag>
   <elementGuidId>42f80fbe-f365-4b65-b8c1-bca9ef28fefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberAnswerField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#numberAnswerField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e748bcb-78b0-4ce0-bf32-bb47991f58c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberAnswerField</value>
      <webElementGuid>84a88dea-d506-453d-ac6e-d80445f3b3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberAnswer</value>
      <webElementGuid>48b1582a-814c-408a-9076-52d845b1e84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element text medium</value>
      <webElementGuid>09e08f03-50a1-46d1-a5e4-4ecd00dc2082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2ab3808-033a-46f4-a969-b71c2d6c76ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8dae3d94-fedc-46c8-b919-ecb2305f0e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberAnswerField&quot;)</value>
      <webElementGuid>ac145827-863f-4243-9467-15867f9d67e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberAnswerField']</value>
      <webElementGuid>3426954b-3c57-4be3-8f9e-58a52c0ac762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='answerForm']/div/div[2]/input</value>
      <webElementGuid>2a611e20-d92f-4d11-ae32-f192b0b3e119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[4]/div/div[2]/input</value>
      <webElementGuid>b602abbb-5e0a-4e69-bcc4-c956123b15d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'numberAnswerField' and @name = 'numberAnswer' and @type = 'text']</value>
      <webElementGuid>7e9a59d3-84b9-440d-8568-2a77222a3f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
