<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Add</name>
   <tag></tag>
   <elementGuidId>558b7144-b2a6-429c-9992-ca1d54acdb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOperationDropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectOperationDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c0e25bb-526d-46ac-9c75-d7a7dd1e17c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>ed5f0bb8-b65b-4d15-8a4b-55b742815cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOperationDropdown</value>
      <webElementGuid>fd7357d7-9381-4c85-963a-623abf095db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectOperation</value>
      <webElementGuid>d1a7ed6a-7576-49be-a7f9-047a62ffeb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>operationChanged(this.preset)</value>
      <webElementGuid>998ff387-813f-44bb-aa08-da8606870e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        </value>
      <webElementGuid>4a66e898-5bc2-400b-b403-a111a20c814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOperationDropdown&quot;)</value>
      <webElementGuid>e3787f27-ae56-49da-bab7-3016b5698c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOperationDropdown']</value>
      <webElementGuid>41cea468-cfca-4125-957c-471a90a69ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[3]/div[2]/select</value>
      <webElementGuid>66835f54-c6b0-441f-8bed-5d899f5f1990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::select[1]</value>
      <webElementGuid>313a40c5-61c8-42a3-9080-d7b22b856da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second number'])[1]/following::select[1]</value>
      <webElementGuid>c6139db8-6165-4fb5-8625-8889bd6ddc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculating ...'])[1]/preceding::select[1]</value>
      <webElementGuid>f34ef3cc-5f80-4ffd-8db0-8dffb8f384b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer'])[1]/preceding::select[1]</value>
      <webElementGuid>ae18b32b-00a5-4441-9052-29fbc9254fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>26a14e5a-2e93-4566-868b-d0243d1153ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOperationDropdown' and @name = 'selectOperation' and (text() = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ' or . = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ')]</value>
      <webElementGuid>22adc145-747b-4cbe-b832-5373caae7b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
