<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Prototype</name>
   <tag></tag>
   <elementGuidId>db939ac1-63de-4397-88a2-00007ba87f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectBuild']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectBuild</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e011e6f-ea91-4213-88e9-882e436e873f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>d3d62a04-eb22-42f1-bf47-eb31e3b80973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>0065ebd1-2713-45b4-82ea-9c4f85c053d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>cb4da5c4-985a-4a9d-8f23-13a83cbb49d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>buildChanged(this.preset)</value>
      <webElementGuid>0b1fe99a-7172-4bb0-9575-fbc12ba680a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      </value>
      <webElementGuid>2e1453e6-6b4c-428c-b7c5-5ea375de6744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectBuild&quot;)</value>
      <webElementGuid>0c3b8daa-ef21-4f31-a073-dcd03ac9906a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectBuild']</value>
      <webElementGuid>ffc603dc-333c-40d9-98cd-27a0254c2682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-body']/div/div/div/div/div[2]/select</value>
      <webElementGuid>c45905a0-e22d-47f3-8c29-79cddbb65173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build'])[1]/following::select[1]</value>
      <webElementGuid>6ff36f28-0f84-4afa-bfe2-c9839fa55b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prototype'])[1]/following::select[1]</value>
      <webElementGuid>6aead35c-d133-4f78-95d0-c076aef5e44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::select[1]</value>
      <webElementGuid>488d793f-9efd-452b-a20c-5b49204c191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First number'])[1]/preceding::select[1]</value>
      <webElementGuid>4704017f-686f-48e6-97b3-c7a84de16983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>31d702d4-d729-422c-a6cd-a317ac2e568a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectBuild' and @name = 'selectBuild' and (text() = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ' or . = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ')]</value>
      <webElementGuid>f3d8c9c9-18bc-4ace-b3bb-ba4b819ff251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
