<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Slower      Slow      Medium      Fa_f36099</name>
   <tag></tag>
   <elementGuidId>c21ba6eb-6837-4f8e-aff2-bc677052284a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#speed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='speed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30984380-e2c0-4d7c-8ccf-4d3bf05d7a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>speed</value>
      <webElementGuid>9325d451-e0bc-4892-905d-399bb81a03fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speed</value>
      <webElementGuid>f8f98fab-7278-4eea-8e9d-b9346a32feb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Slower
      Slow
      Medium
      Fast
      Faster
    </value>
      <webElementGuid>f55c7487-c482-4644-933b-b347356d5c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speed&quot;)</value>
      <webElementGuid>99b72270-6c8d-41b5-bf20-55ef55c69a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='speed']</value>
      <webElementGuid>4d2169c3-3e2b-4cbd-bb6b-3dea5e901577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML6']/div/form/fieldset/select</value>
      <webElementGuid>ac5a50d4-eb64-46ea-882d-413eac6f8736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a speed'])[1]/following::select[1]</value>
      <webElementGuid>b18bec68-ca34-4bac-8699-ba3edafdf5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select menu'])[1]/following::select[1]</value>
      <webElementGuid>6cd41a30-d4f4-4e8a-a130-f3d95aaabc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a file'])[1]/preceding::select[1]</value>
      <webElementGuid>eac1b857-a1e3-40a3-9cc8-51ac289d276b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a number'])[1]/preceding::select[2]</value>
      <webElementGuid>8f2a7333-632e-43ab-8980-71ea76b5ad49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9e3a2d23-d50e-4836-aeff-317251f3cc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'speed' and @id = 'speed' and (text() = '
      Slower
      Slow
      Medium
      Fast
      Faster
    ' or . = '
      Slower
      Slow
      Medium
      Fast
      Faster
    ')]</value>
      <webElementGuid>df9e7d10-1759-43c5-acca-9e39963f372f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
