<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GoogleYahooIphoneBing</name>
   <tag></tag>
   <elementGuidId>174d998d-069f-464d-ac00-a12bee1f5375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#products</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='products']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80f91b94-5e3f-4089-b21b-c12a9c7422ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>products</value>
      <webElementGuid>3971b0d7-066d-4b0a-b3e5-872eb9f1c40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>products</value>
      <webElementGuid>ac8fcd9f-c640-4266-b496-69939d9d23b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		Google
		Yahoo
		Iphone
		Bing
	</value>
      <webElementGuid>9aaafab2-b214-4866-bcc6-ab467e27dacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)</value>
      <webElementGuid>8c2acfc1-c023-418d-8646-7b2472943773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='products']</value>
      <webElementGuid>c7393775-6044-4db9-903c-25c32ec2e548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML6']/div/form/fieldset[2]/select</value>
      <webElementGuid>b5ea0765-5d86-4c1a-8d0c-916d010469e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Product:'])[1]/following::select[1]</value>
      <webElementGuid>32cb8728-4d2b-4848-a822-e72f9ca9afc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a number'])[1]/following::select[2]</value>
      <webElementGuid>2314948c-f2dc-4bd9-8a49-c5cb080adc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Animal:'])[1]/preceding::select[1]</value>
      <webElementGuid>01bf76bf-e5a7-4fa9-9029-68b99b169010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text Labels'])[1]/preceding::select[2]</value>
      <webElementGuid>ad70998d-0073-41fb-a2bd-a742651587d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/select</value>
      <webElementGuid>b8c8b7ad-2d72-45bc-aa9b-ffcb9016cbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'products' and @id = 'products' and (text() = '
		Google
		Yahoo
		Iphone
		Bing
	' or . = '
		Google
		Yahoo
		Iphone
		Bing
	')]</value>
      <webElementGuid>958deab4-60f4-4dd3-a6e4-594091c06ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
