<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Message  12345</name>
   <tag></tag>
   <elementGuidId>635d1dc3-8651-4e1b-b1be-3e374e3f8288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Text1']/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3de5c696-2146-45ef-8495-78d049493915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Message **** 12345</value>
      <webElementGuid>44a10994-3f2a-4108-916a-558a5d46cb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Text1&quot;)/div[@class=&quot;widget-content&quot;]/div[3]/span[1]</value>
      <webElementGuid>90f7a2f9-67e7-43de-a38d-a2702e3377aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Text1']/div/div[3]/span</value>
      <webElementGuid>c2f540de-af10-49c4-9aa7-e8e417c89b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message $ 1234'])[1]/following::span[1]</value>
      <webElementGuid>fae79c66-e4fd-441a-980d-d25fbc4833a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message-123'])[1]/following::span[2]</value>
      <webElementGuid>677a1f5c-972c-40fb-9f2d-0902a06fc8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message &amp;&amp;&amp;123456'])[1]/preceding::span[1]</value>
      <webElementGuid>8a46f4ec-47aa-471b-be23-11021e74585f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message#### 1234567'])[1]/preceding::span[2]</value>
      <webElementGuid>43517d91-4200-4248-9ef1-040472784151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Message **** 12345']/parent::*</value>
      <webElementGuid>d51b3569-2493-4d75-80c8-90b58b1a5b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/span</value>
      <webElementGuid>d0c15231-f444-4f39-9796-5606de78ea0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Message **** 12345' or . = 'Message **** 12345')]</value>
      <webElementGuid>6bfe451e-8c03-4762-a223-88f1214b33f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
