<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>factorialResult</name>
   <tag></tag>
   <elementGuidId>f4b9d143-9f2e-427a-9316-7d77404aea38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='resultDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resultDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>aee9a99f-7fa4-4169-afe5-ad85988bde80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center top-space-20</value>
      <webElementGuid>29ecb3de-c675-4177-80e4-720dccb36609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resultDiv</value>
      <webElementGuid>6f9e6f16-ad78-47cb-806e-3f60f268dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The factorial of 25 is: 1.5511210043330986e+25</value>
      <webElementGuid>bcd1c7a5-6ad2-479f-80e6-fd2c1e69ceaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultDiv&quot;)</value>
      <webElementGuid>3b0931ab-e3d1-4a70-bcb5-69a6a07f4702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='resultDiv']</value>
      <webElementGuid>9477aa92-a694-48e1-8b99-d599b85f6170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate!'])[1]/following::p[1]</value>
      <webElementGuid>73c398d8-ccc4-44d6-a2a2-e9ff6679695d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The greatest factorial calculator!'])[1]/following::p[3]</value>
      <webElementGuid>65f06187-7f6c-49ff-b0b0-1fb9c9fb3263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/preceding::p[1]</value>
      <webElementGuid>d595596c-fb79-4bbb-831d-b67525f27737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::p[1]</value>
      <webElementGuid>cfb7c430-ec2b-4528-b289-4cbe07233c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The factorial of 25 is: 1.5511210043330986e+25']/parent::*</value>
      <webElementGuid>c02dc574-ec93-4d67-9bfb-002eb3379cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/p</value>
      <webElementGuid>f712a189-d3c5-447f-91cf-2ff75a421cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'resultDiv' and (text() = 'The factorial of 25 is: 1.5511210043330986e+25' or . = 'The factorial of 25 is: 1.5511210043330986e+25')]</value>
      <webElementGuid>a4adfdeb-8c12-4a23-91ed-44b34dfdcb4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
