<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_field_21</name>
   <tag></tag>
   <elementGuidId>7b26a016-9ce8-4954-ab42-d46589cacc03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01ca31ec-ba7a-4d54-81d4-d0d4274db1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>243a16c7-8bdc-4f86-95d6-9361800f5ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-21</value>
      <webElementGuid>348cfbc0-df80-4efa-a7a5-de8456cf2dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_21</value>
      <webElementGuid>48cee2c3-5d06-458f-8fea-635920787b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nombre:</value>
      <webElementGuid>12bc71a3-77fb-4b2d-a9f5-654cd052f0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field nombre nom</value>
      <webElementGuid>cc163d0a-7dda-46fe-ab47-255a90c96d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-21</value>
      <webElementGuid>81815d40-2840-4552-adc1-694451d3376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-21&quot;)</value>
      <webElementGuid>d9baeaa6-42a5-41a8-bc59-47ab6ccec0ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-21']</value>
      <webElementGuid>97fcc706-1e45-4a2e-9224-a77534ca2bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-21']/input</value>
      <webElementGuid>e95c57af-e378-4371-8e7e-46a04a8b1e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9fcfc31f-6531-4ea6-9ee1-e0c3981b4678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wsf-1-field-21' and @name = 'field_21' and @placeholder = 'Nombre:']</value>
      <webElementGuid>1b99bd04-4546-4429-9f90-c45d61f21d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
