<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_field_24</name>
   <tag></tag>
   <elementGuidId>5d9739ae-1e86-4f12-a5bd-2ccefb9c529f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e4f54bf-6a83-4637-a1a1-3a8d324df889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6a8781d0-c992-4274-acb3-edc9b80a8982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-24</value>
      <webElementGuid>79639fd0-6338-4071-b502-6afac3ec29b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_24</value>
      <webElementGuid>8df03ce2-f826-43d2-9a38-054627122f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>1deeb7d1-8185-45b7-8cf5-2f2a285eea19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-24</value>
      <webElementGuid>9a84be21-e377-4f83-b530-dd554b014dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-24&quot;)</value>
      <webElementGuid>0fcaba3e-9e6c-411d-9f51-f035f8dfcaca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-24']</value>
      <webElementGuid>7a45554c-a0f3-42d3-b16a-ef1e513b3fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-24']/input</value>
      <webElementGuid>149b1018-39d7-49b5-a196-20729a1da773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>15beaddf-b71a-4cf0-8999-cf041ce497e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'wsf-1-field-24' and @name = 'field_24']</value>
      <webElementGuid>e5668e2c-0687-4c62-b5c4-e5b2ce692a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
