<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_field_23</name>
   <tag></tag>
   <elementGuidId>1b9f43b5-cba3-49c1-9aaf-8c4037589e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bac8228a-6f85-4d1a-8667-ffab87ee1a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2eed47d6-3d41-4603-98c8-ead33c0bc591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-23</value>
      <webElementGuid>fe63954e-c4f5-44a4-adfb-4c99b61ebeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_23</value>
      <webElementGuid>4c03cbfd-1f32-4d0a-a259-e16cae4f14d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>93315961-b6db-46ba-a291-a9cd82263596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>910fcff0-fba3-40a3-a45b-517a3a54c118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-23</value>
      <webElementGuid>5f2caf7e-02a5-4e25-9bbd-f78a1b63674b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78f0644f-6d8f-4f1c-8230-fcf0825aad57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-23&quot;)</value>
      <webElementGuid>b231a5b7-4695-4f91-87f8-1d2f501c3b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-23']</value>
      <webElementGuid>05310747-695b-4e78-a00e-678c0ec02e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-23']/input</value>
      <webElementGuid>662430ad-82b0-490e-9a36-8c8bc8a5e953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f5ea49fd-a77b-4129-8dc4-f72451c65427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wsf-1-field-23' and @name = 'field_23' and @placeholder = 'Email']</value>
      <webElementGuid>b35fdd45-ea97-443d-887f-b1d2fff762e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
