<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nombre</name>
   <tag></tag>
   <elementGuidId>05f7e8f4-70bf-4986-8cdc-b1f372682154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='wsf-1-label-21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-label-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bf305deb-482b-42aa-8299-4001fbe2ed15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-label-21</value>
      <webElementGuid>74457376-7461-4028-8937-2e333836e0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>wsf-1-field-21</value>
      <webElementGuid>c7edb047-731f-4d5b-9e35-f1c37a40f245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-label</value>
      <webElementGuid>35becfa0-5b82-497c-a218-5f06a3f7273d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nombre:</value>
      <webElementGuid>b66de2ca-9343-4665-be79-9b03b652517d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-label-21&quot;)</value>
      <webElementGuid>72d5af12-d2b3-406a-93a8-c075d524742b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='wsf-1-label-21']</value>
      <webElementGuid>e896d8ca-de83-4686-be23-a08eebd563cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-21']/label</value>
      <webElementGuid>7f8e60b6-a1be-42b8-83e1-20475bc0dbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Personales Básicos'])[1]/following::label[1]</value>
      <webElementGuid>8e2209d3-efa2-4414-98e3-5267add495a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacto'])[2]/following::label[1]</value>
      <webElementGuid>94efc60b-04a5-488e-a20b-7aa84b65ebb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide a valid nombre:.'])[1]/preceding::label[1]</value>
      <webElementGuid>6f2c7d32-2799-460c-9753-dfeda124a1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apellidos'])[1]/preceding::label[1]</value>
      <webElementGuid>af6593f9-2500-4796-bb12-81ae31e234ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nombre:']/parent::*</value>
      <webElementGuid>17ee758f-475a-4524-8302-57bef8303b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>576b1190-f43e-4f96-ae7f-17671ecda814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'wsf-1-label-21' and (text() = 'Nombre:' or . = 'Nombre:')]</value>
      <webElementGuid>804020a6-ad14-4d2d-879f-11c1c83e8ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
