<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Direccin_field_28</name>
   <tag></tag>
   <elementGuidId>bdd08d47-9c52-4131-ab38-2d76fa1ff4db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wsf-1-field-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1d4d4c1c-7435-4ca2-8636-a4832b472d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-28</value>
      <webElementGuid>ed04f75c-de97-46cb-8d1e-f7a0f8e7af58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_28</value>
      <webElementGuid>2d4bd02f-2110-4104-95b6-c906c73de9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>c1456915-9bbf-4948-a91c-c91e3092e244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textarea-toolbar</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>a383db33-153a-4d91-a646-cf182fa70d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>2b4b961d-f4e7-4b91-a786-1abe011d89f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>wsf-1-help-28</value>
      <webElementGuid>145978a7-0593-424f-9450-77e416960766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-28</value>
      <webElementGuid>5b94947f-cec2-4270-951b-0c9ad8c4ed65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-28&quot;)</value>
      <webElementGuid>2c0cb54a-bc8d-4f40-977a-2b8c8b0a0036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wsf-1-field-28']</value>
      <webElementGuid>0f72f729-6c78-4312-bdf8-395d88e3434d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-28']/textarea</value>
      <webElementGuid>af0942b9-ff3a-4ade-86d9-9e054ed8bf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>23d1974a-9e62-464f-af03-bd5f9fa0a595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wsf-1-field-28' and @name = 'field_28' and @placeholder = 'Email']</value>
      <webElementGuid>980d692c-a75f-48f1-8c90-b0287d755770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
