<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_WindowsLinuxMac</name>
   <tag></tag>
   <elementGuidId>d9eb1ab6-1e7b-4f64-8fd4-f8040cbec89e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wsf-1-field-53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e87aacd2-b552-413c-9f81-39cea01f62c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-53</value>
      <webElementGuid>8f377ff1-0fae-47c7-8aef-621d6f463188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_53[]</value>
      <webElementGuid>c7ef83aa-319c-4f52-8509-be82e67f2687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>de389d7a-e5cc-423c-8448-11af21902892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-53</value>
      <webElementGuid>76b567eb-3593-4a78-b68c-0d8c4e18a12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WindowsLinuxMac</value>
      <webElementGuid>5e4bba50-485f-416d-8b61-d500f7b5cee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-53&quot;)</value>
      <webElementGuid>8ef431a9-6e91-42b9-993d-e60384bc23bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wsf-1-field-53']</value>
      <webElementGuid>ba2477a1-d3d5-49b0-a4d4-72b3bae9bd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-53']/select</value>
      <webElementGuid>0a5f5126-9b35-4df1-b796-e2ff0b890985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistema operativo'])[1]/following::select[1]</value>
      <webElementGuid>19a5164a-7574-46db-a95c-d2593bfdf128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose a valid radio.'])[1]/following::select[1]</value>
      <webElementGuid>dd20d15d-8d68-41e6-857f-e15ac8f533e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a valid sistema operativo.'])[1]/preceding::select[1]</value>
      <webElementGuid>9e81e845-43ed-45eb-82d7-4cdb35b5d716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>7e0f2227-e0f1-4c6c-b701-68f51eee5ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a6130336-e86c-43b0-8ca3-3db136590aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'wsf-1-field-53' and @name = 'field_53[]' and (text() = 'WindowsLinuxMac' or . = 'WindowsLinuxMac')]</value>
      <webElementGuid>33abaef2-df43-439c-9231-5344d61b000e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
