<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Automation Testing Practice_frame-on_f39fe2</name>
   <tag></tag>
   <elementGuidId>24251bd3-168b-44d2-bc49-8989d612756a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frame-one1434677811</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame-one1434677811']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>26c03c4a-ddb0-4fec-91dd-647fbd4e4529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4944982b-9dbc-4250-9fce-dfb06115a57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame-one1434677811</value>
      <webElementGuid>e2e8b6c6-5459-4633-a07c-4e4b75b5cb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0cfed9c7-d13f-49d9-971e-85f1fb5091c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fs2.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTBHmkDZCZ6tSK_3bsAv-gQi&amp;1434677811&amp;EmbedId=1434677811</value>
      <webElementGuid>784ec488-ad49-4491-a093-42f8f0d46976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1469</value>
      <webElementGuid>3ed3f278-824f-4c00-9523-7a65a4155669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame-one1434677811&quot;)</value>
      <webElementGuid>46dbf724-c5a3-4d92-ac00-3628c00312a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame-one1434677811']</value>
      <webElementGuid>5d6f4ced-abf0-4f60-b428-abb6f910adbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-1307673142697428135']/iframe</value>
      <webElementGuid>f5be0d43-2a89-4c47-b37d-511246dbe5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f91b1fd5-d2d6-4fa3-9572-77c23a532b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'frame-one1434677811' and @src = 'https://fs2.formsite.com/res/showFormEmbed?EParam=m_OmK8apOTBHmkDZCZ6tSK_3bsAv-gQi&amp;1434677811&amp;EmbedId=1434677811']</value>
      <webElementGuid>394a8da8-c76e-4a37-a441-d5e5311283d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
